const data = {
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt1",
      category: "Shirts",
      image: "/images.jpeg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      featuredImage: "/images/banner1.jpg",
      dateCreated: "2021-10-16T11:16:50.198Z",
    },
    {
      name: "Free Shirt",
      slug: "free-shirt2",
      category: "Shirts",
      image: "/2images.jpeg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      featuredImage: "/images/banner1.jpg",
      dateCreated: "2021-10-16T11:16:50.198Z",
    },
    {
      name: "Free Shirt",
      slug: "free-shirt3",
      category: "Shirts",
      image: "/images.jpeg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      featuredImage: "/images/banner1.jpg",
      dateCreated: "2021-10-16T11:16:50.198Z",
    },
    {
      name: "Free Shirt",
      slug: "free-shirt4",
      category: "Shirts",
      image: "/2images.jpeg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      featuredImage: "/images/banner1.jpg",
      dateCreated: "2021-10-16T11:16:50.198Z",
    },
    {
      name: "Free Shirt",
      slug: "free-shirt5",
      category: "Shirts",
      image: "/images.jpeg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      featuredImage: "/images/banner1.jpg",
      dateCreated: "2021-10-16T11:16:50.198Z",
    },
  ],
};

export default data;
